source 'https://rubygems.org'

gem 'sinatra'
gem 'faye-websocket'
gem 'rethinkdb'
gem 'thin'
gem 'haml'
gem 'opal',           :github => 'opal/opal'
gem 'opal-browser',   :github => 'opal/opal-browser'
gem 'opal-jquery',    :github => 'opal/opal-jquery'
gem 'opal-haml',      :github => 'opal/opal-haml'
gem 'react.rb'
gem 'react-source'
